name: ffcccambodia
static_sites:
  - name: web
    github:
      repo: somrachse/FFCC
      branch: main
      deploy_on_push: true
    build_command: npm run build
    output_dir: dist
    catchall_document: index.html
domains:
  - domain: ffcccambodia.com
    type: PRIMARY
  - domain: www.ffcccambodia.com
    type: ALIAS
